# Railway Nixpacks configuration
[variables]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
  nixPkgs = ["nodejs", "npm"]

[phases.install]
  cmds = ["npm ci"]

[phases.build]
  cmds = ["npm run build"]

[phases.deploy]
  startCmd = "npx serve -s dist -p $PORT"