// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhbcnhxxonomxwynojgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoYmNuaHh4b25vbXh3eW5vamdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTExNjEsImV4cCI6MjA3MTUyNzE2MX0.vv3bONHgcXkGB3rZCEHvb8cAizsofr9bL1Daigx0ams";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});